export const GAME_CONFIG = {
  WORLD_WIDTH: 3000,
  WORLD_HEIGHT: 3000,
  
  PLAYER_HEALTH: 100,
  PLAYER_DAMAGE: 10,
  PLAYER_SPEED: 4,
  
  ENEMY_SPEED: 2,
  ENEMY_ATTACK_RANGE: 20, // Melee range
  ENEMY_ATTACK_COOLDOWN: 1500, // ms
  ENEMY_AGGRO_RANGE: 400,

  ENEMY_SPAWN_INTERVAL: 2000, // ms
  MAX_ENEMIES: 20,

  BASE_XP_TO_NEXT_LEVEL: 100,
  XP_PER_LEVEL_MULTIPLIER: 1.5,
};
