export const GAME_CONFIG = {
    WORLD_WIDTH: 3000,
    WORLD_HEIGHT: 3000,
    
    PLAYER_HEALTH: 100,
    PLAYER_DAMAGE: 10,
    PLAYER_SPEED: 4,
    PLAYER_RADIUS: 15,

    ENEMY_SPEED: 2,
    ENEMY_ATTACK_RANGE: 20,
    ENEMY_ATTACK_COOLDOWN: 1000, // ms
    ENEMY_AGGRO_RANGE: 350,
    ENEMY_LEASH_RANGE: 600,

    BASE_XP_TO_NEXT_LEVEL: 100,
    XP_PER_LEVEL_MULTIPLIER: 1.085,
    
    MAX_ENEMIES: 20,
    MAX_LEVEL: 45,

    SAFE_ZONE_RADIUS: 400,
};