export const GAME_CONFIG = {
  WORLD_WIDTH: 2048,
  WORLD_HEIGHT: 1536,
  PLAYER_SPEED: 4,
  PLAYER_HEALTH: 100,
  PLAYER_DAMAGE: 10,
  ENEMY_SPEED: 2,
  ENEMY_AGGRO_RANGE: 300,
  ENEMY_ATTACK_RANGE: 20,
  ENEMY_ATTACK_COOLDOWN: 1000, // ms
  ENEMY_SPAWN_RATE: 2000, // ms
  XP_PER_LEVEL_MULTIPLIER: 1.5,
  BASE_XP_TO_NEXT_LEVEL: 100,
};